"""Initial migration

Revision ID: 3f9b025794eb
Revises: 
Create Date: 2025-05-20 17:29:10.873220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9b025794eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('vehicle_year', sa.Integer(), nullable=True),
    sa.Column('car_make', sa.String(length=100), nullable=True),
    sa.Column('car_model', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('callback_number', sa.String(length=20), nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('lead_score', sa.Float(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_modified_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callbacks_callback_number'), 'callbacks', ['callback_number'], unique=False)
    op.create_index(op.f('ix_callbacks_id'), 'callbacks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_callbacks_id'), table_name='callbacks')
    op.drop_index(op.f('ix_callbacks_callback_number'), table_name='callbacks')
    op.drop_table('callbacks')
    # ### end Alembic commands ###